# SPDX-License-Identifier: Apache-2.0
# # Copyright Contributors to the ODPi Egeria project.
#
name: Build Images on Dockerhub and Quay.io

on:
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # QEMU is needed for ARM64 build 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1  
      - name: Set Release version env variable
        run: |
          echo "VERSION=2.13-3.0.0" >> $GITHUB_ENV        
      # For main code stream we push the image and add the latest tag
      - name: Build and push (master merge)
        id: docker_build_master
        uses: docker/build-push-action@v2
        with:
          push:  true
          tags: tcnthomas/kafka:${{ env.VERSION }}, tcnthomas/kafka:latest
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
